# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: List all available commands
    cmd: task --list-all

  deps:
    desc: Install dependencies the project
    cmds:
      - go mod download
      - task: deps:tailwind

  deps:tailwind:
    desc: Download Tailwind CSS standalone binaries
    cmd: go run ./scripts/download-tailwind

  ci:
    desc: Run full CI pipeline (deps, format, test, lint, build)
    cmds:
      - task: deps
      - task: format
      - task: test
      - task: test:e2e
      - task: lint
      - task: build

  install:
    desc: Install the project locally (using go install)
    cmd: go install ./cmd/veta/.

  build:
    desc: Build the project locally
    cmd: go build -o ./dist/veta ./cmd/veta/.

  release:
    desc: Build all production release artifacts
    cmds:
      - task: ci
      - go run ./scripts/release

  format:
    desc: Run formatters
    cmds:
      - golangci-lint fmt ./...
      - dprint fmt --config ./dprint.json --log-level warn

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...
      - dprint check --config ./dprint.json --log-level warn

  test:
    desc: Run tests
    cmds:
      - go test ./...
      - go test -race ./...

  test:e2e:
    desc: Run end-to-end tests
    cmd: go test -tags=e2e -count=1 ./e2e
