package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type releaseArtifact struct {
	Name   string `json:"name"`
	SHA256 string `json:"sha256"`
}

type releaseManifest struct {
	Artifacts []releaseArtifact `json:"artifacts"`
}

const (
	formulaDir  = "Formula"
	githubRepo  = "varavelio/veta"
	projectDesc = "Veta static site generator"
	projectHome = "https://github.com/varavelio/veta"
)

// main runs the Homebrew formula generator and owns process exit behavior.
func main() {
	if err := run(context.Background()); err != nil {
		fmt.Fprintf(os.Stderr, "generate homebrew formula: %s\n", err)
		os.Exit(1)
	}
}

// run generates current and pinned Veta Homebrew formula files.
func run(ctx context.Context) error {
	if len(os.Args) < 2 || len(os.Args) > 3 {
		return fmt.Errorf("usage: go run ./integrations/installers/brew vx.y.z [tap-root]")
	}

	version := normalizeVersion(os.Args[1])
	outputRoot := "."
	if len(os.Args) == 3 {
		outputRoot = os.Args[2]
	}

	hashes, err := fetchManifest(ctx, manifestURL(version))
	if err != nil {
		return err
	}

	currentFile := "veta.rb"
	if strings.Contains(version, "-") {
		currentFile = "veta-next.rb"
	}
	pinnedFile := "veta@" + version + ".rb"

	if err := writeFormula(outputRoot, currentFile, version, hashes); err != nil {
		return err
	}
	if strings.Contains(version, "-") {
		return nil
	}
	if err := writeFormula(outputRoot, pinnedFile, version, hashes); err != nil {
		return err
	}

	return nil
}

// writeFormula writes one Homebrew formula file.
func writeFormula(outputRoot, fileName, version string, hashes map[string]string) error {
	content, err := generateFormula(fileName, version, hashes)
	if err != nil {
		return err
	}
	directory := filepath.Join(outputRoot, filepath.FromSlash(formulaDir))
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create formula directory: %w", err)
	}
	path := filepath.Join(directory, fileName)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", fileName, err)
	}

	return nil
}

// generateFormula returns Ruby formula content for one formula filename.
func generateFormula(fileName, version string, hashes map[string]string) (string, error) {
	required := []string{
		"veta_darwin_arm64.tar.gz",
		"veta_darwin_amd64.tar.gz",
		"veta_linux_arm64.tar.gz",
		"veta_linux_amd64.tar.gz",
	}
	for _, name := range required {
		if hashes[name] == "" {
			return "", fmt.Errorf("checksum for %s is missing", name)
		}
	}

	baseURL := releaseBaseURL(version)
	var builder strings.Builder
	builder.WriteString("# This file was generated by the Veta release workflow. DO NOT EDIT.\n")
	fmt.Fprintf(&builder, "class %s < Formula\n", formulaClassName(fileName))
	fmt.Fprintf(&builder, "  desc %q\n", projectDesc)
	fmt.Fprintf(&builder, "  homepage %q\n", projectHome)
	builder.WriteString("  license \"MIT\"\n")
	fmt.Fprintf(&builder, "  version %q\n\n", version)
	builder.WriteString("  on_macos do\n")
	builder.WriteString("    if Hardware::CPU.arm?\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/veta_darwin_arm64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["veta_darwin_arm64.tar.gz"])
	builder.WriteString("    else\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/veta_darwin_amd64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["veta_darwin_amd64.tar.gz"])
	builder.WriteString("    end\n")
	builder.WriteString("  end\n\n")
	builder.WriteString("  on_linux do\n")
	builder.WriteString("    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/veta_linux_arm64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["veta_linux_arm64.tar.gz"])
	builder.WriteString("    else\n")
	fmt.Fprintf(&builder, "      url %q\n", baseURL+"/veta_linux_amd64.tar.gz")
	fmt.Fprintf(&builder, "      sha256 %q\n", hashes["veta_linux_amd64.tar.gz"])
	builder.WriteString("    end\n")
	builder.WriteString("  end\n\n")
	builder.WriteString("  def install\n")
	builder.WriteString("    bin.install \"veta\"\n")
	builder.WriteString("  end\n\n")
	builder.WriteString("  test do\n")
	builder.WriteString("    system \"#{bin}/veta\", \"--version\"\n")
	builder.WriteString("  end\n")
	builder.WriteString("end\n")

	return builder.String(), nil
}

// fetchManifest downloads manifest.json and returns filename to hash values.
func fetchManifest(ctx context.Context, url string) (map[string]string, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("create manifest request: %w", err)
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("download manifest: %w", err)
	}
	defer func() {
		_ = response.Body.Close()
	}()
	if response.StatusCode >= http.StatusBadRequest {
		return nil, fmt.Errorf("download manifest: %s", response.Status)
	}
	content, err := io.ReadAll(response.Body)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	return parseManifest(content)
}

// parseManifest parses manifest.json content.
func parseManifest(content []byte) (map[string]string, error) {
	var manifest releaseManifest
	if err := json.Unmarshal(content, &manifest); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}

	checksums := map[string]string{}
	for _, artifact := range manifest.Artifacts {
		if artifact.Name == "" || artifact.SHA256 == "" {
			return nil, fmt.Errorf("invalid manifest artifact: name and sha256 are required")
		}
		checksums[artifact.Name] = artifact.SHA256
	}

	return checksums, nil
}

// manifestURL returns the release manifest URL for version.
func manifestURL(version string) string {
	return releaseBaseURL(version) + "/manifest.json"
}

// releaseBaseURL returns the GitHub release base URL for version.
func releaseBaseURL(version string) string {
	return "https://github.com/" + githubRepo + "/releases/download/v" + version
}

// normalizeVersion returns version without a leading v prefix.
func normalizeVersion(version string) string {
	version = strings.TrimSpace(strings.ToLower(version))
	return strings.TrimPrefix(version, "v")
}

// formulaClassName returns the Ruby class name for fileName.
func formulaClassName(fileName string) string {
	name := strings.TrimSuffix(fileName, ".rb")
	var builder strings.Builder
	capitalizeNext := true
	for _, char := range name {
		if isASCIIAlphanumeric(char) {
			if capitalizeNext {
				builder.WriteRune(unicode.ToUpper(char))
				capitalizeNext = false
				continue
			}
			builder.WriteRune(char)
			continue
		}
		if char == '@' {
			builder.WriteString("AT")
		}
		capitalizeNext = true
	}

	return builder.String()
}

// isASCIIAlphanumeric reports whether char is an ASCII letter or digit.
func isASCIIAlphanumeric(char rune) bool {
	return char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9'
}
